name: build-windows-binary
on:
  workflow_call:
    inputs:
      rockstar_version:
        required: true
        type: string
        default: "v0.0.0-test"
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up .NET 9 SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.x'
      - name: update version constant
        run: |
          (Get-content Starship/Rockstar.Engine/RockstarEnvironment.cs)
          | Foreach-Object {$_ -replace "VERSION = ""[^""]+"";", "VERSION = ""${{ inputs.rockstar_version }}"";"}
          | Set-Content Starship/Rockstar.Engine/RockstarEnvironment.cs
      - name: dotnet publish Windows x64 binary
        run: dotnet publish Starship/Rockstar -o rockstar-windows-x64-binary -c Release
      - name: Test Windows x64 binary
        run:
          rockstar-windows-x64-binary/rockstar.exe --version
      - name: upload rockstar-windows-x64-binary
        uses: actions/upload-artifact@v4
        with:
          name: rockstar-windows-x64-binary
          path: rockstar-windows-x64-binary
