name: build-macos-binary
on:
  workflow_call:
    inputs:
      rockstar_version:
        required: true
        type: string
        default: "v0.0.0-test"
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore workloads
        working-directory: ./Starship
        run: dotnet workload restore

      - name: Patch VERSION constant inside Starship/Rockstar.Engine/RockstarEnvironment.cs
        run: sed -i "" 's/VERSION = "[^"]*";/VERSION = "${{ inputs.rockstar_version }}";/g' Starship/Rockstar.Engine/RockstarEnvironment.cs
      - name: dotnet publish macos x64 binary
        working-directory: ./Starship
        run: dotnet publish Rockstar -o ../rockstar-macos-x64-binary -r osx-x64 -c Release
      - name: dotnet publish macos ARM64 binary
        working-directory: ./Starship
        run: dotnet publish Rockstar -o ../rockstar-macos-arm64-binary -r osx-arm64 -c Release
      - name: Test ARM64 binary
        run:
          rockstar-macos-arm64-binary/rockstar --version
      - name: upload rockstar-macos-x64-binary
        uses: actions/upload-artifact@v4
        with:
          name: rockstar-macos-x64-binary
          path: rockstar-macos-x64-binary
      - name: upload rockstar-macos-arm64-binary
        uses: actions/upload-artifact@v4
        with:
          name: rockstar-macos-arm64-binary
          path: rockstar-macos-arm64-binary
